# Generated by Django 5.0.6 on 2024-07-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla_t_toners_municipios',
            name='zona',
            field=models.CharField(choices=[('SIN DEFINIR', 'SIN DEFINIR'), ('SUR', 'SUR'), ('NORTE', 'NORTE')], default='SIN DEFINIR', max_length=11),
        ),
    ]
