# Generated by Django 5.0 on 2024-04-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tonner',
            old_name='N_Tonner',
            new_name='Numero_Tonner',
        ),
    ]
