# Generated by Django 5.0.6 on 2024-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='firmas/')),
            ],
        ),
        migrations.AlterField(
            model_name='retiro_tonner',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
