# Generated by Django 5.0.6 on 2024-07-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_firma_alter_retiro_tonner_firma'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Firma',
        ),
    ]
