# Generated by Django 5.0 on 2024-04-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0002_rename_n_tonner_tonner_numero_tonner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonner',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
