# Generated by Django 5.0 on 2024-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0003_alter_tonner_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro_tonner',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
