# Generated by Django 5.0 on 2024-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0005_tabla_t_toners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_t_toners',
            name='marca',
            field=models.CharField(choices=[('N/A', 'N/A'), ('HP', 'HP'), ('SAMSUNG', 'SAMSUNG'), ('KYOSERA', 'KYOSERA'), ('EPSON', 'EPSON')], default='N/A', max_length=7),
        ),
    ]
