# Generated by Django 5.0 on 2024-04-23 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0008_delete_generar_reporte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_t_toners',
            old_name='t_toner',
            new_name='toner_de_impresora',
        ),
    ]
