# Generated by Django 5.0 on 2024-04-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0009_rename_t_toner_tabla_t_toners_toner_de_impresora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabla_t_toners',
            old_name='cantidad_t',
            new_name='cantidad_toner',
        ),
    ]
