# Generated by Django 5.0 on 2024-04-25 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0010_rename_cantidad_t_tabla_t_toners_cantidad_toner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toner_Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recarga', models.PositiveIntegerField()),
                ('fecha_recarga', models.DateTimeField(auto_now_add=True)),
                ('retiro_tonner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toner_recarga', to='Datos.retiro_tonner')),
            ],
        ),
    ]
