# Generated by Django 5.0 on 2024-04-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0011_toner_recarga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla_T_Toners_Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficina', models.CharField(max_length=50)),
                ('activo', models.CharField(max_length=30)),
                ('numero_impresoras', models.PositiveIntegerField()),
                ('referencia', models.CharField(max_length=100)),
                ('marca', models.CharField(choices=[('N/A', 'N/A'), ('HP', 'HP'), ('SAMSUNG', 'SAMSUNG'), ('KYOSERA', 'KYOSERA'), ('EPSON', 'EPSON')], default='N/A', max_length=7)),
                ('toner_de_impresora', models.CharField(choices=[('105A', '105A'), ('30A', '30A'), ('83A', '83A'), ('136A', '136A'), ('175A', '175A'), ('17A', '17A'), ('19A', '19A'), ('85A', '85A'), ('226A', '226A'), ('D1015', 'D1015'), ('TINTA', 'TINTA'), ('N/A', 'N/A')], default='N/A', max_length=5)),
                ('otro_toner', models.CharField(choices=[('105A', '105A'), ('30A', '30A'), ('83A', '83A'), ('136A', '136A'), ('175A', '175A'), ('17A', '17A'), ('19A', '19A'), ('85A', '85A'), ('226A', '226A'), ('D1015', 'D1015'), ('TINTA', 'TINTA'), ('N/A', 'N/A')], default='N/A', max_length=5)),
                ('cantidad_toner', models.PositiveBigIntegerField()),
                ('comprobado', models.CharField(choices=[('S', 'SI'), ('N', 'NO'), ('R', 'REGISTRAR')], default='S', max_length=1)),
            ],
        ),
    ]
