# Generated by Django 5.0 on 2024-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0012_tabla_t_toners_municipios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_t_toners_municipios',
            name='comprobado',
            field=models.CharField(choices=[('S', 'SI'), ('N', 'NO'), ('R', 'REGISTRAR')], default='SI', max_length=9),
        ),
    ]
