# Generated by Django 5.0 on 2024-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0013_alter_tabla_t_toners_municipios_comprobado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabla_t_toners_municipios',
            name='comprobado',
            field=models.CharField(choices=[('SI', 'SI'), ('NO', 'NO'), ('REGISTRAR', 'REGISTRAR')], default='SI', max_length=9),
        ),
    ]
