# Generated by Django 5.0 on 2024-04-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0015_alter_tabla_t_toners_municipios_otro_toner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recargar_Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_Recargar', models.PositiveIntegerField()),
                ('fecha_Recarga', models.DateTimeField(auto_now_add=True)),
                ('toner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Datos.tonner')),
            ],
        ),
    ]
