# Generated by Django 5.0 on 2024-04-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0018_toner_m_recargados_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner_m_recargados',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('RECARGANDO', 'RECARGANDO')], default='RECARGANDO', max_length=10),
        ),
    ]
