# Generated by Django 5.0 on 2024-05-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0020_toner_m_recargados_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner_m_recargados',
            name='fecha_entrega',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
