# Generated by Django 5.0 on 2024-05-16 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0021_alter_toner_m_recargados_fecha_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tonner',
            old_name='Numero_Tonner',
            new_name='Numero_Toner',
        ),
    ]
