# Generated by Django 5.0 on 2024-05-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0022_rename_numero_tonner_tonner_numero_toner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tonner',
            name='Estado',
        ),
    ]
