# Generated by Django 5.0 on 2024-05-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0023_remove_tonner_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tonner',
            name='Estado',
            field=models.CharField(choices=[('Recargando', 'Recargando'), ('Disponible', 'Disponible'), ('En Uso', 'En Uso')], default='L', max_length=10),
        ),
    ]
