# Generated by Django 5.0 on 2024-05-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0024_tonner_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tonner',
            name='Estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Recargando', 'Recargando'), ('En Uso', 'En Uso')], default='Disponible', max_length=10),
        ),
    ]
