# Generated by Django 5.0 on 2024-05-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0025_alter_tonner_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='retiro_tonner',
            name='caso_GLPI',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tonner',
            name='Estado',
            field=models.CharField(choices=[('Disponible', 'Disponible')], default='Disponible', max_length=10),
        ),
    ]
