# Generated by Django 5.0 on 2024-05-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0026_retiro_tonner_caso_glpi_alter_tonner_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro_tonner',
            name='caso_GLPI',
            field=models.PositiveIntegerField(default='N/A'),
        ),
    ]
