# Generated by Django 5.0 on 2024-05-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0027_alter_retiro_tonner_caso_glpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retiro_tonner',
            name='caso_GLPI',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
