# Generated by Django 5.0 on 2024-05-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datos', '0028_alter_area_nombre_alter_retiro_tonner_caso_glpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro_tonner',
            name='cantidad_retirada',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
